Repository WallarooLabs/wallaroo, pull requests merged in 2018-03, with the labels that each got.

#2038 Update MonHub to resolve #1824 and #1193
  monitoring_hub/apps/metrics_reporter/lib/metrics_reporter/latency_stats_calculator.ex
  monitoring_hub/apps/metrics_reporter_ui/lib/metrics_reporter_ui/latency_stats_broadcaster/supervisor.ex
  monitoring_hub/apps/metrics_reporter_ui/lib/metrics_reporter_ui/latency_stats_broadcaster/worker.ex
  monitoring_hub/apps/metrics_reporter_ui/lib/metrics_reporter_ui/throughput_stats_broadcaster/supervisor.ex
  monitoring_hub/apps/metrics_reporter_ui/lib/metrics_reporter_ui/throughput_stats_broadcaster/worker.ex
  monitoring_hub/apps/metrics_reporter_ui/lib/metrics_reporter_ui/throughputs_broadcaster/supervisor.ex
  monitoring_hub/apps/metrics_reporter_ui/lib/metrics_reporter_ui/throughputs_broadcaster/worker.ex
  monitoring_hub/apps/metrics_reporter_ui/package.json
  monitoring_hub/apps/metrics_reporter_ui/test/channels/ingress_egress_channel_test.exs
  monitoring_hub/apps/metrics_reporter_ui/test/channels/source_sink_channel_test.exs
  monitoring_hub/apps/metrics_reporter_ui/test/channels/step_channel_test.exs
  monitoring_hub/apps/metrics_reporter_ui/web/channels/computation_by_worker_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/computation_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/ingress_egress_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/metrics_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/node_ingress_egress_by_pipeline_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/node_ingress_egress_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/pipeline_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/pipeline_ingestion_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/source_sink_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/start_end_by_worker_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/start_end_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/channels/step_channel.ex
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/AppNav.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/Applications.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/IngestionSourceDashboard.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/IngestionSourceDashboardContainer.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/IngestionSourceTableBodyContainer.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/IngestionSourcesTable.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/MonitoringGraphs.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/MonitoringGraphsContainer.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/SourceDashboard.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/SourceDashboardContainer.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/SourceListPanel.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/SourceTableBodyContainer.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/components/sources/SourcesTable.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/stores/LatencyPercentageBinsStore.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/stores/LatencyPercentileBinStatsStore.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/stores/ThroughputStatsStore.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/buffy-ui/stores/ThroughputsStore.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/components/charts/chartBuilders/LineChartBuilder.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/util/BenchmarksHelpers.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/util/Duration.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/util/Format.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/util/ListHelpers.js
  monitoring_hub/apps/metrics_reporter_ui/web/static/js/util/Precision.js
  monitoring_hub/apps/monitoring_hub_utils/lib/monitoring_hub_utils/helpers.ex
  monitoring_hub/apps/monitoring_hub_utils/lib/monitoring_hub_utils/stores/app_config_store.ex
Labels: DO NOT MERGE

#2073 Correctly remove boundary references when worker leaves
  lib/wallaroo/core/common/producer_consumer.pony
  lib/wallaroo/core/source/kafka_source/kafka_source.pony
  lib/wallaroo/core/source/kafka_source/kafka_source_listener.pony
  lib/wallaroo/core/source/source.pony
  lib/wallaroo/core/source/tcp_source/tcp_source.pony
  lib/wallaroo/core/source/tcp_source/tcp_source_listener.pony
  lib/wallaroo/core/topology/steps.pony
  lib/wallaroo/ent/router_registry/router_registry.pony
Labels: changelog - fixed

#2081 Add partition count observability query
  lib/wallaroo/core/initialization/local_topology.pony
  lib/wallaroo/ent/network/external_channel_tcp.pony
  lib/wallaroo/ent/router_registry/router_registry.pony
  lib/wallaroo_labs/messages/external_messages.pony
  lib/wallaroo_labs/query/query_json.pony
  testing/tools/external_sender/external_sender.pony
Labels: changelog - added, observability

#2086 Inform joining worker to shut down on join error
  lib/wallaroo/core/initialization/local_topology.pony
  lib/wallaroo/core/messages/channel_messages.pony
  lib/wallaroo/ent/network/control_channel_tcp.pony
  lib/wallaroo/ent/router_registry/router_registry.pony
Labels: changelog - added

#2120 Add sleeping python pipeline for benchmarking
  testing/performance/apps/python/sleepy_python/.gitignore
  testing/performance/apps/python/sleepy_python/Makefile
  testing/performance/apps/python/sleepy_python/README.md
  testing/performance/apps/python/sleepy_python/gen.py
  testing/performance/apps/python/sleepy_python/sleepy.py
Labels: test
