Repository WallarooLabs/wallaroo, pull requests merged in 2019-12, with the labels that each got.

#3074 Fix race between 1st checkpoint token, 2PC intro done, barrier complete
  lib/wallaroo/core/sink/connector_sink/connector_sink.pony
  lib/wallaroo/core/sink/connector_sink/connector_sink_twopc.pony
Labels: connectors, resilience

#3080 Address connection timing bugs in OutgoingBoundary
  lib/wallaroo/core/boundary/boundary.pony
  lib/wallaroo/core/data_channel/data_channel.pony
  lib/wallaroo/core/messages/channel_messages.pony
  lib/wallaroo/core/recovery/recovery.pony
  lib/wallaroo/core/recovery/recovery_phase.pony
Labels: resilience

#3085 Allow duplicate deactivate_stream ops for a stream ID in GlobalStreamRegistry
  lib/wallaroo/core/source/connector_source/connector_framed_source_notify.pony
  lib/wallaroo/core/source/connector_source/connector_source.pony
  lib/wallaroo/core/source/connector_source/connector_stream_registry.pony
Labels: connectors, resilience

#3087 Add multi-key input and output checking to master-crasher.sh
  testing/correctness/scripts/effectively-once/1-to-1-passthrough-verify.sh
  testing/correctness/scripts/effectively-once/README.md
  testing/correctness/scripts/effectively-once/create-input-files.sh
  testing/correctness/scripts/effectively-once/delete-input-files.sh
  testing/correctness/scripts/effectively-once/master-crasher.sh
  testing/correctness/scripts/effectively-once/sample-env-vars.sh
  testing/correctness/scripts/effectively-once/sample-env-vars.sh.tcp-source+sink
  testing/correctness/tests/aloc_sink/Makefile
  testing/correctness/tests/aloc_sink/aloc_sink_impl.py
  testing/correctness/tests/aloc_sink/run_aloc_sink_test.validate.sh
Labels: test

#3095 Skip boundary reconnect phases if there's only one worker
  lib/wallaroo/core/recovery/recovery.pony
Labels: resilience
